//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Table()
        {
            this.Author_Table = new HashSet<Author_Table>();
            this.Defaulter_Table = new HashSet<Defaulter_Table>();
            this.IssuedBook_Table = new HashSet<IssuedBook_Table>();
            this.Publisher_Table = new HashSet<Publisher_Table>();
        }
    
        public int Book_ID { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public string PublisherName { get; set; }
        public string Language { get; set; }
        public string Edition { get; set; }
        public string BookCost { get; set; }
        public string Actual_Stock { get; set; }
        public string Current_Stock { get; set; }
        public byte[] Book_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author_Table> Author_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defaulter_Table> Defaulter_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuedBook_Table> IssuedBook_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publisher_Table> Publisher_Table { get; set; }
    }
}
