//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharityFund_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharityFund_Table()
        {
            this.Contributor_Table = new HashSet<Contributor_Table>();
        }
    
        public int Fund_ID { get; set; }
        public string FundTittle { get; set; }
        public string Description { get; set; }
        public string Bkash_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contributor_Table> Contributor_Table { get; set; }
    }
}
