//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contributor_Table
    {
        public int Contributor_ID { get; set; }
        public string ContributorName { get; set; }
        public Nullable<int> Fund_ID { get; set; }
        public string Email { get; set; }
        public string Contact_No { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string Amount { get; set; }
    
        public virtual Admin_Table Admin_Table { get; set; }
        public virtual CharityFund_Table CharityFund_Table { get; set; }
        public virtual Member_Table Member_Table { get; set; }
    }
}
