//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defaulter_Table
    {
        public int Defaulter_ID { get; set; }
        public int Member_ID { get; set; }
        public string MemberName { get; set; }
        public string Contact_No { get; set; }
        public int Book_ID { get; set; }
    
        public virtual Book_Table Book_Table { get; set; }
        public virtual Member_Table Member_Table { get; set; }
    }
}
