//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedBook_Table
    {
        public int IssuedBook_ID { get; set; }
        public int Member_ID { get; set; }
        public int Book_ID { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Book_Table Book_Table { get; set; }
        public virtual Member_Table Member_Table { get; set; }
    }
}
