//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin_Table
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Admin_Table()
    {
        this.Contributor_Table = new HashSet<Contributor_Table>();
    }

    public int Admin_ID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Contact_No { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contributor_Table> Contributor_Table { get; set; }
}

public partial class Author_Table
{
    public int Author_ID { get; set; }
    public string AuthorName { get; set; }
    public Nullable<int> Book_ID { get; set; }

    public virtual Book_Table Book_Table { get; set; }
}

public partial class Book_Table
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book_Table()
    {
        this.Author_Table = new HashSet<Author_Table>();
        this.Defaulter_Table = new HashSet<Defaulter_Table>();
        this.IssuedBook_Table = new HashSet<IssuedBook_Table>();
        this.Publisher_Table = new HashSet<Publisher_Table>();
    }

    public int Book_ID { get; set; }
    public string BookName { get; set; }
    public string AuthorName { get; set; }
    public string PublisherName { get; set; }
    public string Language { get; set; }
    public string Edition { get; set; }
    public string BookCost { get; set; }
    public string Actual_Stock { get; set; }
    public string Current_Stock { get; set; }
    public byte[] Book_Image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Author_Table> Author_Table { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Defaulter_Table> Defaulter_Table { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<IssuedBook_Table> IssuedBook_Table { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Publisher_Table> Publisher_Table { get; set; }
}

public partial class CharityFund_Table
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CharityFund_Table()
    {
        this.Contributor_Table = new HashSet<Contributor_Table>();
    }

    public int Fund_ID { get; set; }
    public string FundTittle { get; set; }
    public string Description { get; set; }
    public string Bkash_No { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contributor_Table> Contributor_Table { get; set; }
}

public partial class Contributor_Table
{
    public int Contributor_ID { get; set; }
    public string ContributorName { get; set; }
    public Nullable<int> Fund_ID { get; set; }
    public string Email { get; set; }
    public string Contact_No { get; set; }
    public Nullable<int> admin_id { get; set; }
    public Nullable<int> member_id { get; set; }
    public string Amount { get; set; }

    public virtual Admin_Table Admin_Table { get; set; }
    public virtual CharityFund_Table CharityFund_Table { get; set; }
    public virtual Member_Table Member_Table { get; set; }
}

public partial class Defaulter_Table
{
    public int Defaulter_ID { get; set; }
    public int Member_ID { get; set; }
    public string MemberName { get; set; }
    public string Contact_No { get; set; }
    public int Book_ID { get; set; }

    public virtual Book_Table Book_Table { get; set; }
    public virtual Member_Table Member_Table { get; set; }
}

public partial class IssuedBook_Table
{
    public int IssuedBook_ID { get; set; }
    public int Member_ID { get; set; }
    public int Book_ID { get; set; }
    public Nullable<System.DateTime> IssuedDate { get; set; }
    public Nullable<System.DateTime> DueDate { get; set; }

    public virtual Book_Table Book_Table { get; set; }
    public virtual Member_Table Member_Table { get; set; }
}

public partial class Member_Table
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member_Table()
    {
        this.Contributor_Table = new HashSet<Contributor_Table>();
        this.Defaulter_Table = new HashSet<Defaulter_Table>();
        this.IssuedBook_Table = new HashSet<IssuedBook_Table>();
    }

    public int Member_ID { get; set; }
    public string FullName { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Contact_No { get; set; }
    public string City { get; set; }
    public string Area { get; set; }
    public string account_status { get; set; }
    public string Email { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contributor_Table> Contributor_Table { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Defaulter_Table> Defaulter_Table { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<IssuedBook_Table> IssuedBook_Table { get; set; }
}

public partial class Publisher_Table
{
    public int Publisher_ID { get; set; }
    public string PublisherName { get; set; }
    public Nullable<int> Book_ID { get; set; }

    public virtual Book_Table Book_Table { get; set; }
}
